# Generated by Django 5.2.1 on 2025-05-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
