# Generated by Django 5.2.1 on 2025-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_role_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph', models.CharField(blank=True, max_length=350, null=True)),
                ('paragraph1', models.CharField(blank=True, max_length=340, null=True)),
                ('skillName', models.CharField(blank=True, max_length=50, null=True)),
                ('skillpercent', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
