# Generated by Django 5.2.1 on 2025-05-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_skill_remove_about_skillname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='paragraph',
            field=models.CharField(blank=True, max_length=650, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='paragraph1',
            field=models.CharField(blank=True, max_length=940, null=True),
        ),
    ]
